/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package thrift;

import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.apache.thrift.*;
import org.apache.thrift.async.*;
import org.apache.thrift.meta_data.*;
import org.apache.thrift.transport.*;
import org.apache.thrift.protocol.*;

// No additional import required for struct/union.

public class DogInfoRequest implements TBase<DogInfoRequest, DogInfoRequest._Fields>, java.io.Serializable, Cloneable {
  private static final TStruct STRUCT_DESC = new TStruct("DogInfoRequest");

  private static final TField DOG_BREEDS_FIELD_DESC = new TField("dogBreeds", TType.LIST, (short)1);


  public List<String> dogBreeds;

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements TFieldIdEnum {
    DOG_BREEDS((short)1, "dogBreeds");
  
    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();
  
    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOG_BREEDS
  	return DOG_BREEDS;
        default:
  	return null;
      }
    }
  
    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }
  
    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }
  
    private final short _thriftId;
    private final String _fieldName;
  
    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }
  
    public short getThriftFieldId() {
      return _thriftId;
    }
  
    public String getFieldName() {
      return _fieldName;
    }
  }


  // isset id assignments

  public static final Map<_Fields, FieldMetaData> metaDataMap;
  static {
    Map<_Fields, FieldMetaData> tmpMap = new EnumMap<_Fields, FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOG_BREEDS, new FieldMetaData("dogBreeds", TFieldRequirementType.DEFAULT,
      new ListMetaData(TType.LIST,
                new FieldValueMetaData(TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    FieldMetaData.addStructMetaDataMap(DogInfoRequest.class, metaDataMap);
  }


  public DogInfoRequest() {
  }

  public DogInfoRequest(
    List<String> dogBreeds)
  {
    this();
    this.dogBreeds = dogBreeds;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DogInfoRequest(DogInfoRequest other) {
    if (other.isSetDogBreeds()) {
      List<String> __this__dogBreeds = new ArrayList<String>();
      for (String other_element : other.dogBreeds) {
        __this__dogBreeds.add(other_element);
      }
      this.dogBreeds = __this__dogBreeds;
    }
  }

  public DogInfoRequest deepCopy() {
    return new DogInfoRequest(this);
  }

  @Override
  public void clear() {
    this.dogBreeds = null;
  }

  public int getDogBreedsSize() {
    return (this.dogBreeds == null) ? 0 : this.dogBreeds.size();
  }

  public java.util.Iterator<String> getDogBreedsIterator() {
    return (this.dogBreeds == null) ? null : this.dogBreeds.iterator();
  }

  public void addToDogBreeds(String elem) {
    if (this.dogBreeds == null) {
      this.dogBreeds = new ArrayList<String>();
    }
    this.dogBreeds.add(elem);
  }

  public List<String> getDogBreeds() {
    return this.dogBreeds;
  }

  public DogInfoRequest setDogBreeds(List<String> dogBreeds) {
    this.dogBreeds = dogBreeds;
    
    return this;
  }

  public void unsetDogBreeds() {
    this.dogBreeds = null;
  }

  /** Returns true if field dogBreeds is set (has been asigned a value) and false otherwise */
  public boolean isSetDogBreeds() {
    return this.dogBreeds != null;
  }

  public void setDogBreedsIsSet(boolean value) {
    if (!value) {
      this.dogBreeds = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DOG_BREEDS:
      if (value == null) {
        unsetDogBreeds();
      } else {
        setDogBreeds((List<String>)value);
      }
      break;
    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DOG_BREEDS:
      return getDogBreeds();
    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been asigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DOG_BREEDS:
      return isSetDogBreeds();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DogInfoRequest)
      return this.equals((DogInfoRequest)that);
    return false;
  }

  public boolean equals(DogInfoRequest that) {
    if (that == null)
      return false;
    boolean this_present_dogBreeds = true && this.isSetDogBreeds();
    boolean that_present_dogBreeds = true && that.isSetDogBreeds();
    if (this_present_dogBreeds || that_present_dogBreeds) {
      if (!(this_present_dogBreeds && that_present_dogBreeds))
        return false;
      if (!this.dogBreeds.equals(that.dogBreeds))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();
    boolean present_dogBreeds = true && (isSetDogBreeds());
    builder.append(present_dogBreeds);
    if (present_dogBreeds)
      builder.append(dogBreeds);
    return builder.toHashCode();
  }

  public int compareTo(DogInfoRequest other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    DogInfoRequest typedOther = (DogInfoRequest)other;

    lastComparison = Boolean.valueOf(isSetDogBreeds()).compareTo(typedOther.isSetDogBreeds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDogBreeds()) {
      lastComparison = TBaseHelper.compareTo(this.dogBreeds, typedOther.dogBreeds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) {
        break;
      }
      switch (field.id) {
        case 1: // DOG_BREEDS
          if (field.type == TType.LIST) {
            {
            TList _list0 = iprot.readListBegin();
            this.dogBreeds = new ArrayList<String>(_list0.size);
            for (int _i1 = 0; _i1 < _list0.size; ++_i1)
            {
              String _elem2;
              _elem2 = iprot.readString();
              this.dogBreeds.add(_elem2);
            }
            iprot.readListEnd();
            }
          } else {
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();

    // check for required fields of primitive type, which can't be checked in the validate method
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();
    
    oprot.writeStructBegin(STRUCT_DESC);
    if (this.dogBreeds != null) {
      oprot.writeFieldBegin(DOG_BREEDS_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRING, this.dogBreeds.size()));
        for (String _iter3 : this.dogBreeds)
        {
          oprot.writeString(_iter3);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DogInfoRequest(");
    boolean first = true;
    sb.append("dogBreeds:");
    if (this.dogBreeds == null) {
      sb.append("null");
    } else {
      sb.append(this.dogBreeds);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws TException {
    // check for required fields
  }
}
